language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - docker
env:
  global:
    - WHEEL_PLATFORM=manylinux2014_x86_64
    - WHEEL_DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64
before_script:
  # Fix python path for usage with sudo; fix scripts permissions
  - sudo sed -i '/^Defaults\tsecure_path.*$/ d' /etc/sudoers
  - sudo chmod +x build_pip_pkg.sh
  - sudo chmod +x build_tokenizer.sh
  # Install required packages
  - sudo apt-get update && sudo apt-get install -y wget rsync gcc g++ cmake
  # Build and install OpenNMT Tokenizer static library
  - ./build_tokenizer.sh sudo
  # Upgrade pip, install TensorFlow
  - sudo -H pip install --upgrade pip
  - sudo -H pip install tensorflow
script:
  - cd $TRAVIS_BUILD_DIR
  - sudo make tf_onmttok_pip_pkg tf_onmttok_test
after_success:
  - |
    if [[ -n $TRAVIS_TAG ]]; then
        docker pull $WHEEL_DOCKER_IMAGE
        docker run -v `pwd`:/io -w /io $WHEEL_DOCKER_IMAGE bash ./auditwheel.sh repair --plat $WHEEL_PLATFORM artifacts/*.whl
        pip install twine
        twine upload wheelhouse/*.whl
    fi
